/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cmina_openmeeting_fragment_MyPageFragment */

#ifndef _Included_com_example_cmina_openmeeting_fragment_MyPageFragment
#define _Included_com_example_cmina_openmeeting_fragment_MyPageFragment
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_cmina_openmeeting_fragment_MyPageFragment_REQ_CODE_SELECT_IMAGE
#define com_example_cmina_openmeeting_fragment_MyPageFragment_REQ_CODE_SELECT_IMAGE 3001L
/*
 * Class:     com_example_cmina_openmeeting_fragment_MyPageFragment
 * Method:    loadCascade
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_cmina_openmeeting_fragment_MyPageFragment_loadCascade
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_cmina_openmeeting_fragment_MyPageFragment
 * Method:    detect
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_cmina_openmeeting_fragment_MyPageFragment_detect
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
